name: Build and publish Nuget package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  PROJECT_PATH: 'SolversLibrary'
  OUTPUT_PATH: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json

jobs:
  build:
    name: 'Build and Publish Nuget'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Restore packages
      run: dotnet restore ${{ env.PROJECT_PATH }}
    - name: Build library
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
    - name: Get version
      id: version
      uses: battila7/get-version-action@v2
    - name: Pack
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore -c Release -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.OUTPUT_PATH }}
    - name: Publish
      run: dotnet nuget push ${{ env.OUTPUT_PATH }}/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source ${{ env.NUGET_SOURCE_URL }}
