name: Build and publish Nuget package

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
    - SolversLibrary/*
    - .github/workflows/build-pack.yml
  pull_request:
    branches: [ "master" ]
    paths:
    - SolversLibrary/*
    - .github/workflows/build-pack.yml

jobs:
  build:
    name: 'Build and Publish Nuget'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build library
      run: dotnet build --configuration Release
    - name: Pack
      run: |
        cd SolversLibrary
        dotnet pack -c Release -o out
    - name: Publish
      run: dotnet nuget push SolversLibrary.1.0.0.nupkg --api-key ${NUGET_KEY} --source https://api.nuget.org/v3/index.json
      env:
       NUGET_KEY: ${{ secrets.NUGET_KEY }} 
